Send =s to stderr in gits and add xw function in which.sh

diff --git a/bin/gits b/bin/gits
--- a/bin/gits
+++ b/bin/gits
@@ -48,7 +48,7 @@ if [[ $cmd == clone ]]; then
 fi
 
 if [ ! -d "$dir" ]; then
-    echo "error: not a directory: $2"
+    echo "error: not a directory: $2" >&2
     exit 1
 fi
 
@@ -59,10 +59,10 @@ find -L "$dir" -maxdepth 4 -type d -name .git -exec dirname '{}' ';' | while rea
 
     # now we know it's a repo
 
-    echo "================="
-    push "$repo"
+    echo "=================" >&2
+    push "$repo" >&2
     git "$@"
-    pop
+    pop >&2
 done
-echo "================="
+echo "=================" >&2
 popd >/dev/null
